# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php

sudo: false

php: 
 - 5.3

env:
  matrix:
    - DB=MYSQL CORE_RELEASE=master

matrix:
  include:
    - php: 5.3
      env: DB=PGSQL CORE_RELEASE=master
    - php: 5.4
      env: DB=MYSQL CORE_RELEASE=master
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=master

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script: 
 - phpunit testsession/tests/unit/
